addpath(genpath('./'))
addpath(genpath('~/circstat-matlab/'))
init_paths;
load(strcat(ftr_path, '/AP/FIG/S1_Expert_Combo_Adjusted/Cortex/Spontaneous_Alpha_Modulation/data.mat'))
out_path = true;
alpha_modulated = out.alpha_modulated;

s1 = load(strcat(ftr_path, '/AP/FIG/S1_Expert_Combo_Adjusted/Cortex/Spontaneous_Alpha_Modulation/data.mat'));
pfc = load(strcat(ftr_path, '/AP/FIG/PFC_Expert_Combo_Adjusted/PFC/Spontaneous_Alpha_Modulation/data.mat'));
striatum = load(strcat(ftr_path, '/AP/FIG/S1_Expert_Combo_Adjusted/Basal_Ganglia/Spontaneous_Alpha_Modulation/data.mat'));
amygdala = load(strcat(ftr_path, '/AP/FIG/S1_Expert_Combo_Adjusted/Amygdala/Spontaneous_Alpha_Modulation/data.mat'));

s1.out.alpha_modulated = s1.out.alpha_modulated(cell2mat(s1.out.alpha_modulated.avg_trial_fr) > 0.5, :);
striatum.out.alpha_modulated = striatum.out.alpha_modulated(cell2mat(striatum.out.alpha_modulated.avg_trial_fr) > 0.5, :);
amygdala.out.alpha_modulated = amygdala.out.alpha_modulated(cell2mat(amygdala.out.alpha_modulated.avg_trial_fr) > 0.5, :);
pfc.out.alpha_modulated = pfc.out.alpha_modulated(cell2mat(pfc.out.alpha_modulated.avg_trial_fr) > 0.5, :);

exinds = load('ExcldInds/3738_excld_v2.mat');
for i = 1:length(exinds.new_excld{1})
    session_id = exinds.new_excld{1}{i};
    cid = exinds.new_excld{2}{i};
    s1.out.alpha_modulated(strcmp(s1.out.alpha_modulated.session_id, session_id) & s1.out.alpha_modulated.cluster_id == cid,:) = [];
    striatum.out.alpha_modulated(strcmp(striatum.out.alpha_modulated.session_id, session_id) & striatum.out.alpha_modulated.cluster_id == cid,:) = [];
    amygdala.out.alpha_modulated(strcmp(amygdala.out.alpha_modulated.session_id, session_id) & amygdala.out.alpha_modulated.cluster_id == cid,:) = [];
end
exinds = load('ExcldInds/3387_excld.mat');
for i = 1:length(exinds.excld{1})
    session_id = exinds.excld{1}{i};
    cid = exinds.excld{2}{i};
    s1.out.alpha_modulated(strcmp(s1.out.alpha_modulated.session_id, session_id) & s1.out.alpha_modulated.cluster_id == cid,:) = [];
    striatum.out.alpha_modulated(strcmp(striatum.out.alpha_modulated.session_id, session_id) & striatum.out.alpha_modulated.cluster_id == cid,:) = [];
    amygdala.out.alpha_modulated(strcmp(amygdala.out.alpha_modulated.session_id, session_id) & amygdala.out.alpha_modulated.cluster_id == cid,:) = [];
end

inds = find(contains(pfc.out.alpha_modulated.region, 'AC') & strcmp(pfc.out.alpha_modulated.waveform_class, 'RS') & cell2mat(pfc.out.alpha_modulated.avg_trial_fr) > 15);
for i = 1:length(inds)
    pfc.out.alpha_modulated(inds(i),:).waveform_class{1} = 'FS';
end

exinds = load('ExcldInds/1075_excld.mat');
for i = 1:length(exinds.excld{1})
    session_id = exinds.excld{1}{i};
    cid = exinds.excld{2}{i};
    pfc.out.alpha_modulated(strcmp(pfc.out.alpha_modulated.session_id, session_id) & pfc.out.alpha_modulated.cluster_id == cid,:) = [];
end
exinds = load('ExcldInds/3755_excld.mat');
for i = 1:length(exinds.excld{1})
    session_id = exinds.excld{1}{i};
    cid = exinds.excld{2}{i};
    pfc.out.alpha_modulated(strcmp(pfc.out.alpha_modulated.session_id, session_id) & pfc.out.alpha_modulated.cluster_id == cid,:) = [];
end

pfc_rs = pfc.out.alpha_modulated(strcmp(pfc.out.alpha_modulated.waveform_class,'RS'),:);
pfc_fs = pfc.out.alpha_modulated(strcmp(pfc.out.alpha_modulated.waveform_class,'FS'),:);
s1_rs = s1.out.alpha_modulated(strcmp(s1.out.alpha_modulated.waveform_class,'RS'),:);
s1_fs = s1.out.alpha_modulated(strcmp(s1.out.alpha_modulated.waveform_class,'FS'),:);
striatum_rs = striatum.out.alpha_modulated(strcmp(striatum.out.alpha_modulated.waveform_class,'RS'),:);
striatum_fs = striatum.out.alpha_modulated(strcmp(striatum.out.alpha_modulated.waveform_class,'FS'),:);
amygdala_rs = amygdala.out.alpha_modulated(strcmp(amygdala.out.alpha_modulated.waveform_class,'RS'),:);
amygdala_fs = amygdala.out.alpha_modulated(strcmp(amygdala.out.alpha_modulated.waveform_class,'FS'),:);

pfc_rs_session_ids = unique(pfc_rs.session_id);
for s = 1:length(pfc_rs_session_ids)
    tmp = pfc_rs(strcmp(pfc_rs.session_id, pfc_rs_session_ids{s}),:);
    pfc_rs_fracs_lick(s) = sum(tmp.p_lick < pfc.out.overall_p_threshold) / size(tmp,1) * 100;
    pfc_rs_fracs_nolick(s) = sum(tmp.p_nolick < pfc.out.overall_p_threshold) / size(tmp,1) * 100;
end
pfc_fs_session_ids = unique(pfc_fs.session_id);
for s = 1:length(pfc_fs_session_ids)
    tmp = pfc_fs(strcmp(pfc_fs.session_id, pfc_fs_session_ids{s}),:);
    pfc_fs_fracs_lick(s) = sum(tmp.p_lick < pfc.out.overall_p_threshold) / size(tmp,1) * 100;
    pfc_fs_fracs_nolick(s) = sum(tmp.p_nolick < pfc.out.overall_p_threshold) / size(tmp,1) * 100;
end
s1_rs_session_ids = unique(s1_rs.session_id);
for s = 1:length(s1_rs_session_ids)
    tmp = s1_rs(strcmp(s1_rs.session_id, s1_rs_session_ids{s}),:);
    s1_rs_fracs_lick(s) = sum(tmp.p_lick < s1.out.overall_p_threshold) / size(tmp,1) * 100;
    s1_rs_fracs_nolick(s) = sum(tmp.p_nolick < s1.out.overall_p_threshold) / size(tmp,1) * 100;
end
s1_fs_session_ids = unique(s1_fs.session_id);
for s = 1:length(s1_fs_session_ids)
    tmp = s1_fs(strcmp(s1_fs.session_id, s1_fs_session_ids{s}),:);
    s1_fs_fracs_lick(s) = sum(tmp.p_lick < s1.out.overall_p_threshold) / size(tmp,1) * 100;
    s1_fs_fracs_nolick(s) = sum(tmp.p_nolick < s1.out.overall_p_threshold) / size(tmp,1) * 100;
end
striatum_rs_session_ids = unique(striatum_rs.session_id);
for s = 1:length(striatum_rs_session_ids)
    tmp = striatum_rs(strcmp(striatum_rs.session_id, striatum_rs_session_ids{s}),:);
    striatum_rs_fracs_lick(s) = sum(tmp.p_lick < striatum.out.overall_p_threshold) / size(tmp,1) * 100;
    striatum_rs_fracs_nolick(s) = sum(tmp.p_nolick < striatum.out.overall_p_threshold) / size(tmp,1) * 100;
end
striatum_fs_session_ids = unique(striatum_fs.session_id);
for s = 1:length(striatum_fs_session_ids)
    tmp = striatum_fs(strcmp(striatum_fs.session_id, striatum_fs_session_ids{s}),:);
    striatum_fs_fracs_lick(s) = sum(tmp.p_lick < striatum.out.overall_p_threshold) / size(tmp,1) * 100;
    striatum_fs_fracs_nolick(s) = sum(tmp.p_nolick < striatum.out.overall_p_threshold) / size(tmp,1) * 100;
end
amygdala_rs_session_ids = unique(amygdala_rs.session_id);
for s = 1:length(amygdala_rs_session_ids)
    tmp = amygdala_rs(strcmp(amygdala_rs.session_id, amygdala_rs_session_ids{s}),:);
    amygdala_rs_fracs_lick(s) = sum(tmp.p_lick < amygdala.out.overall_p_threshold) / size(tmp,1) * 100;
    amygdala_rs_fracs_nolick(s) = sum(tmp.p_nolick < amygdala.out.overall_p_threshold) / size(tmp,1) * 100;
end
amygdala_fs_session_ids = unique(amygdala_fs.session_id);
for s = 1:length(amygdala_fs_session_ids)
    tmp = amygdala_fs(strcmp(amygdala_fs.session_id, amygdala_fs_session_ids{s}),:);
    amygdala_fs_fracs_lick(s) = sum(tmp.p_lick < amygdala.out.overall_p_threshold) / size(tmp,1) * 100;
    amygdala_fs_fracs_nolick(s) = sum(tmp.p_nolick < amygdala.out.overall_p_threshold) / size(tmp,1) * 100;
end
% pfc_rs_session_ids = unique(pfc_rs.session_id);
% for s = 1:length(pfc_rs_session_ids)
%     tmp = pfc_rs(strcmp(pfc_rs.session_id, pfc_rs_session_ids{s}),:);
%     pfc_rs_fracs_lick(s) = sum(tmp.p_lick < 0.01) / size(tmp,1) * 100;
%     pfc_rs_fracs_nolick(s) = sum(tmp.p_nolick < 0.01) / size(tmp,1) * 100;
% end
% pfc_fs_session_ids = unique(pfc_fs.session_id);
% for s = 1:length(pfc_fs_session_ids)
%     tmp = pfc_fs(strcmp(pfc_fs.session_id, pfc_fs_session_ids{s}),:);
%     pfc_fs_fracs_lick(s) = sum(tmp.p_lick < 0.01) / size(tmp,1) * 100;
%     pfc_fs_fracs_nolick(s) = sum(tmp.p_nolick < 0.01) / size(tmp,1) * 100;
% end
% s1_rs_session_ids = unique(s1_rs.session_id);
% for s = 1:length(s1_rs_session_ids)
%     tmp = s1_rs(strcmp(s1_rs.session_id, s1_rs_session_ids{s}),:);
%     s1_rs_fracs_lick(s) = sum(tmp.p_lick < 0.01) / size(tmp,1) * 100;
%     s1_rs_fracs_nolick(s) = sum(tmp.p_nolick < 0.01) / size(tmp,1) * 100;
% end
% s1_fs_session_ids = unique(s1_fs.session_id);
% for s = 1:length(s1_fs_session_ids)
%     tmp = s1_fs(strcmp(s1_fs.session_id, s1_fs_session_ids{s}),:);
%     s1_fs_fracs_lick(s) = sum(tmp.p_lick < 0.01) / size(tmp,1) * 100;
%     s1_fs_fracs_nolick(s) = sum(tmp.p_nolick < 0.01) / size(tmp,1) * 100;
% end
% striatum_rs_session_ids = unique(striatum_rs.session_id);
% for s = 1:length(striatum_rs_session_ids)
%     tmp = striatum_rs(strcmp(striatum_rs.session_id, striatum_rs_session_ids{s}),:);
%     striatum_rs_fracs_lick(s) = sum(tmp.p_lick < 0.01) / size(tmp,1) * 100;
%     striatum_rs_fracs_nolick(s) = sum(tmp.p_nolick < 0.01) / size(tmp,1) * 100;
% end
% striatum_fs_session_ids = unique(striatum_fs.session_id);
% for s = 1:length(striatum_fs_session_ids)
%     tmp = striatum_fs(strcmp(striatum_fs.session_id, striatum_fs_session_ids{s}),:);
%     striatum_fs_fracs_lick(s) = sum(tmp.p_lick < 0.01) / size(tmp,1) * 100;
%     striatum_fs_fracs_nolick(s) = sum(tmp.p_nolick < 0.01) / size(tmp,1) * 100;
% end
% amygdala_rs_session_ids = unique(amygdala_rs.session_id);
% for s = 1:length(amygdala_rs_session_ids)
%     tmp = amygdala_rs(strcmp(amygdala_rs.session_id, amygdala_rs_session_ids{s}),:);
%     amygdala_rs_fracs_lick(s) = sum(tmp.p_lick < 0.01) / size(tmp,1) * 100;
%     amygdala_rs_fracs_nolick(s) = sum(tmp.p_nolick < 0.01) / size(tmp,1) * 100;
% end
% amygdala_fs_session_ids = unique(amygdala_fs.session_id);
% for s = 1:length(amygdala_fs_session_ids)
%     tmp = amygdala_fs(strcmp(amygdala_fs.session_id, amygdala_fs_session_ids{s}),:);
%     amygdala_fs_fracs_lick(s) = sum(tmp.p_lick < 0.01) / size(tmp,1) * 100;
%     amygdala_fs_fracs_nolick(s) = sum(tmp.p_nolick < 0.01) / size(tmp,1) * 100;
% end

summary_fig = figure('Position', [1220 1334 1000 700]);
tl = tiledlayout(2,2);
axs(1) = nexttile;
hold on
bar([2,5,8,11,14,17, 20, 23], ...
    [nanmean(s1_rs_fracs_lick), nanmean(s1_fs_fracs_lick), ...
    nanmean(pfc_rs_fracs_lick), nanmean(pfc_fs_fracs_lick), ...
    nanmean(striatum_rs_fracs_lick), nanmean(striatum_fs_fracs_lick), ...
    nanmean(amygdala_rs_fracs_lick), nanmean(amygdala_fs_fracs_lick)], 0.3, ...
    'EdgeColor', 'k', 'FaceColor', 'b')
bar([1,4,7,10,13,16,19,22], ...
    [nanmean(s1_rs_fracs_nolick), nanmean(s1_fs_fracs_nolick), ...
    nanmean(pfc_rs_fracs_nolick), nanmean(pfc_fs_fracs_nolick), ...
    nanmean(striatum_rs_fracs_nolick), nanmean(striatum_fs_fracs_nolick), ...
    nanmean(amygdala_rs_fracs_nolick), nanmean(amygdala_fs_fracs_nolick)], 0.3, ...
    'EdgeColor', 'k', 'FaceColor', 'r')
errorbar([2,5,8,11,14,17, 20, 23], ...
    [nanmean(s1_rs_fracs_lick), nanmean(s1_fs_fracs_lick), ...
    nanmean(pfc_rs_fracs_lick), nanmean(pfc_fs_fracs_lick), ...
    nanmean(striatum_rs_fracs_lick), nanmean(striatum_fs_fracs_lick), ...
    nanmean(amygdala_rs_fracs_lick), nanmean(amygdala_fs_fracs_lick)], ...
    [ste(s1_rs_fracs_lick), ste(s1_fs_fracs_lick), ...
    ste(pfc_rs_fracs_lick), ste(pfc_fs_fracs_lick), ...
    ste(striatum_rs_fracs_lick), ste(striatum_fs_fracs_lick), ...
    ste(amygdala_rs_fracs_lick), ste(amygdala_fs_fracs_lick)], ...
    'k.')
errorbar([1,4,7,10,13,16,19,22], ...
    [nanmean(s1_rs_fracs_nolick), nanmean(s1_fs_fracs_nolick), ...
    nanmean(pfc_rs_fracs_nolick), nanmean(pfc_fs_fracs_nolick), ...
    nanmean(striatum_rs_fracs_nolick), nanmean(striatum_fs_fracs_nolick), ...
    nanmean(amygdala_rs_fracs_nolick), nanmean(amygdala_fs_fracs_nolick)], ...
    [ste(s1_rs_fracs_nolick), ste(s1_fs_fracs_nolick), ...
    ste(pfc_rs_fracs_nolick), ste(pfc_fs_fracs_nolick), ...
    ste(striatum_rs_fracs_nolick), ste(striatum_fs_fracs_nolick), ...
    ste(amygdala_rs_fracs_nolick), ste(amygdala_fs_fracs_nolick)], ...
    'k.')
axs(2) = nexttile;
hold on
bar([2,5,8,11,14,17, 20, 23], ...
    [nanmean(s1_rs.pmi_lick), nanmean(s1_fs.pmi_lick), ...
    nanmean(pfc_rs.pmi_lick), nanmean(pfc_fs.pmi_lick), ...
    nanmean(striatum_rs.pmi_lick), nanmean(striatum_fs.pmi_lick), ...
    nanmean(amygdala_rs.pmi_lick), nanmean(amygdala_fs.pmi_lick)], 0.3, ...
    'EdgeColor', 'k', 'FaceColor', 'b')
bar([1,4,7,10,13,16,19,22], ...
    [nanmean(s1_rs.pmi_nolick), nanmean(s1_fs.pmi_nolick), ...
    nanmean(pfc_rs.pmi_nolick), nanmean(pfc_fs.pmi_nolick), ...
    nanmean(striatum_rs.pmi_nolick), nanmean(striatum_fs.pmi_nolick), ...
    nanmean(amygdala_rs.pmi_nolick), nanmean(amygdala_fs.pmi_nolick)], 0.3, ...
    'EdgeColor', 'k', 'FaceColor', 'r')
errorbar([2,5,8,11,14,17, 20, 23], ...
    [nanmean(s1_rs.pmi_lick), nanmean(s1_fs.pmi_lick), ...
    nanmean(pfc_rs.pmi_lick), nanmean(pfc_fs.pmi_lick), ...
    nanmean(striatum_rs.pmi_lick), nanmean(striatum_fs.pmi_lick), ...
    nanmean(amygdala_rs.pmi_lick), nanmean(amygdala_fs.pmi_lick)], ...
    [ste(s1_rs.pmi_lick), ste(s1_fs.pmi_lick), ...
    ste(pfc_rs.pmi_lick), ste(pfc_fs.pmi_lick), ...
    ste(striatum_rs.pmi_lick), ste(striatum_fs.pmi_lick), ...
    ste(amygdala_rs.pmi_lick), ste(amygdala_fs.pmi_lick)], ...
    'k.')
errorbar([1,4,7,10,13,16,19,22], ...
    [nanmean(s1_rs.pmi_nolick), nanmean(s1_fs.pmi_nolick), ...
    nanmean(pfc_rs.pmi_nolick), nanmean(pfc_fs.pmi_nolick), ...
    nanmean(striatum_rs.pmi_nolick), nanmean(striatum_fs.pmi_nolick), ...
    nanmean(amygdala_rs.pmi_nolick), nanmean(amygdala_fs.pmi_nolick)], ...
    [ste(s1_rs.pmi_nolick), ste(s1_fs.pmi_nolick), ...
    ste(pfc_rs.pmi_nolick), ste(pfc_fs.pmi_nolick), ...
    ste(striatum_rs.pmi_nolick), ste(striatum_fs.pmi_nolick), ...
    ste(amygdala_rs.pmi_nolick), ste(amygdala_fs.pmi_nolick)], ...
    'k.')
axs(3) = nexttile;
hold on
bar([2,5,8,11,14,17, 20, 23], ...
    [nanmean(s1_rs.mses_lick), nanmean(s1_fs.mses_lick), ...
    nanmean(pfc_rs.mses_lick), nanmean(pfc_fs.mses_lick), ...
    nanmean(striatum_rs.mses_lick), nanmean(striatum_fs.mses_lick), ...
    nanmean(amygdala_rs.mses_lick), nanmean(amygdala_fs.mses_lick)], 0.3, ...
    'EdgeColor', 'k', 'FaceColor', 'b')
bar([1,4,7,10,13,16,19,22], ...
    [nanmean(s1_rs.mses_nolick), nanmean(s1_fs.mses_nolick), ...
    nanmean(pfc_rs.mses_nolick), nanmean(pfc_fs.mses_nolick), ...
    nanmean(striatum_rs.mses_nolick), nanmean(striatum_fs.mses_nolick), ...
    nanmean(amygdala_rs.mses_nolick), nanmean(amygdala_fs.mses_nolick)], 0.3, ...
    'EdgeColor', 'k', 'FaceColor', 'r')
errorbar([2,5,8,11,14,17, 20, 23], ...
    [nanmean(s1_rs.mses_lick), nanmean(s1_fs.mses_lick), ...
    nanmean(pfc_rs.mses_lick), nanmean(pfc_fs.mses_lick), ...
    nanmean(striatum_rs.mses_lick), nanmean(striatum_fs.mses_lick), ...
    nanmean(amygdala_rs.mses_lick), nanmean(amygdala_fs.mses_lick)], ...
    [ste(s1_rs.mses_lick), ste(s1_fs.mses_lick), ...
    ste(pfc_rs.mses_lick), ste(pfc_fs.mses_lick), ...
    ste(striatum_rs.mses_lick), ste(striatum_fs.mses_lick), ...
    ste(amygdala_rs.mses_lick), ste(amygdala_fs.mses_lick)], ...
    'k.')
errorbar([1,4,7,10,13,16,19,22], ...
    [nanmean(s1_rs.mses_nolick), nanmean(s1_fs.mses_nolick), ...
    nanmean(pfc_rs.mses_nolick), nanmean(pfc_fs.mses_nolick), ...
    nanmean(striatum_rs.mses_nolick), nanmean(striatum_fs.mses_nolick), ...
    nanmean(amygdala_rs.mses_nolick), nanmean(amygdala_fs.mses_nolick)], ...
    [ste(s1_rs.mses_nolick), ste(s1_fs.mses_nolick), ...
    ste(pfc_rs.mses_nolick), ste(pfc_fs.mses_nolick), ...
    ste(striatum_rs.mses_nolick), ste(striatum_fs.mses_nolick), ...
    ste(amygdala_rs.mses_nolick), ste(amygdala_fs.mses_nolick)], ...
    'k.')

s1_rs_theta_bars_lick = s1_rs.theta_bars_lick;
pfc_rs_theta_bars_lick = pfc_rs.theta_bars_lick;
striatum_rs_theta_bars_lick = striatum_rs.theta_bars_lick;
amygdala_rs_theta_bars_lick = amygdala_rs.theta_bars_lick;
s1_fs_theta_bars_lick = s1_fs.theta_bars_lick;
pfc_fs_theta_bars_lick = pfc_fs.theta_bars_lick;
striatum_fs_theta_bars_lick = striatum_fs.theta_bars_lick;
amygdala_fs_theta_bars_lick = amygdala_fs.theta_bars_lick;

s1_rs_theta_bars_lick = s1_rs_theta_bars_lick(~isnan(s1_rs_theta_bars_lick));
pfc_rs_theta_bars_lick = pfc_rs_theta_bars_lick(~isnan(pfc_rs_theta_bars_lick));
striatum_rs_theta_bars_lick = striatum_rs_theta_bars_lick(~isnan(striatum_rs_theta_bars_lick));
amygdala_rs_theta_bars_lick = amygdala_rs_theta_bars_lick(~isnan(amygdala_rs_theta_bars_lick));
s1_fs_theta_bars_lick = s1_fs_theta_bars_lick(~isnan(s1_fs_theta_bars_lick));
pfc_fs_theta_bars_lick = pfc_fs_theta_bars_lick(~isnan(pfc_fs_theta_bars_lick));
striatum_fs_theta_bars_lick = striatum_fs_theta_bars_lick(~isnan(striatum_fs_theta_bars_lick));
amygdala_fs_theta_bars_lick = amygdala_fs_theta_bars_lick(~isnan(amygdala_fs_theta_bars_lick));

s1_rs_theta_bars_nolick = s1_rs.theta_bars_nolick;
pfc_rs_theta_bars_nolick = pfc_rs.theta_bars_nolick;
striatum_rs_theta_bars_nolick = striatum_rs.theta_bars_nolick;
amygdala_rs_theta_bars_nolick = amygdala_rs.theta_bars_nolick;
s1_fs_theta_bars_nolick = s1_fs.theta_bars_nolick;
pfc_fs_theta_bars_nolick = pfc_fs.theta_bars_nolick;
striatum_fs_theta_bars_nolick = striatum_fs.theta_bars_nolick;
amygdala_fs_theta_bars_nolick = amygdala_fs.theta_bars_nolick;

s1_rs_theta_bars_nolick = s1_rs_theta_bars_nolick(~isnan(s1_rs_theta_bars_nolick));
pfc_rs_theta_bars_nolick = pfc_rs_theta_bars_nolick(~isnan(pfc_rs_theta_bars_nolick));
striatum_rs_theta_bars_nolick = striatum_rs_theta_bars_nolick(~isnan(striatum_rs_theta_bars_nolick));
amygdala_rs_theta_bars_nolick = amygdala_rs_theta_bars_nolick(~isnan(amygdala_rs_theta_bars_nolick));
s1_fs_theta_bars_nolick = s1_fs_theta_bars_nolick(~isnan(s1_fs_theta_bars_nolick));
pfc_fs_theta_bars_nolick = pfc_fs_theta_bars_nolick(~isnan(pfc_fs_theta_bars_nolick));
striatum_fs_theta_bars_nolick = striatum_fs_theta_bars_nolick(~isnan(striatum_fs_theta_bars_nolick));
amygdala_fs_theta_bars_nolick = amygdala_fs_theta_bars_nolick(~isnan(amygdala_fs_theta_bars_nolick));

axs(4) = nexttile;
hold on
bar([2,5,8,11,14,17, 20, 23], ...
    [circ_mean(s1_rs_theta_bars_lick), circ_mean(s1_fs_theta_bars_lick), ...
    circ_mean(pfc_rs_theta_bars_lick), circ_mean(pfc_fs_theta_bars_lick), ...
    circ_mean(striatum_rs_theta_bars_lick), circ_mean(striatum_fs_theta_bars_lick), ...
    circ_mean(amygdala_rs_theta_bars_lick), circ_mean(amygdala_fs_theta_bars_lick)], 0.3, ...
    'EdgeColor', 'k', 'FaceColor', 'b')
bar([1,4,7,10,13,16,19,22], ...
    [circ_mean(s1_rs_theta_bars_nolick), circ_mean(s1_fs_theta_bars_nolick), ...
    circ_mean(pfc_rs_theta_bars_nolick), circ_mean(pfc_fs_theta_bars_nolick), ...
    circ_mean(striatum_rs_theta_bars_nolick), circ_mean(striatum_fs_theta_bars_nolick), ...
    circ_mean(amygdala_rs_theta_bars_nolick), circ_mean(amygdala_fs_theta_bars_nolick)], 0.3, ...
    'EdgeColor', 'k', 'FaceColor', 'r')
errorbar([2,5,8,11,14,17, 20, 23], ...
    [circ_mean(s1_rs_theta_bars_lick), circ_mean(s1_fs_theta_bars_lick), ...
    circ_mean(pfc_rs_theta_bars_lick), circ_mean(pfc_fs_theta_bars_lick), ...
    circ_mean(striatum_rs_theta_bars_lick), circ_mean(striatum_fs_theta_bars_lick), ...
    circ_mean(amygdala_rs_theta_bars_lick), circ_mean(amygdala_fs_theta_bars_lick)], ...
    [circ_ste(s1_rs_theta_bars_lick), circ_ste(s1_fs_theta_bars_lick), ...
    circ_ste(pfc_rs_theta_bars_lick), circ_ste(pfc_fs_theta_bars_lick), ...
    circ_ste(striatum_rs_theta_bars_lick), circ_ste(striatum_fs_theta_bars_lick), ...
    circ_ste(amygdala_rs_theta_bars_lick), circ_ste(amygdala_fs_theta_bars_lick)], ...
    'k.')
errorbar([1,4,7,10,13,16,19,22], ...
    [circ_mean(s1_rs_theta_bars_nolick), circ_mean(s1_fs_theta_bars_nolick), ...
    circ_mean(pfc_rs_theta_bars_nolick), circ_mean(pfc_fs_theta_bars_nolick), ...
    circ_mean(striatum_rs_theta_bars_nolick), circ_mean(striatum_fs_theta_bars_nolick), ...
    circ_mean(amygdala_rs_theta_bars_nolick), circ_mean(amygdala_fs_theta_bars_nolick)], ...
    [circ_ste(s1_rs_theta_bars_nolick), circ_ste(s1_fs_theta_bars_nolick), ...
    circ_ste(pfc_rs_theta_bars_nolick), circ_ste(pfc_fs_theta_bars_nolick), ...
    circ_ste(striatum_rs_theta_bars_nolick), circ_ste(striatum_fs_theta_bars_nolick), ...
    circ_ste(amygdala_rs_theta_bars_nolick), circ_ste(amygdala_fs_theta_bars_nolick)], ...
    'k.')

all_phase_mod = combineTables(s1.out.alpha_modulated, pfc.out.alpha_modulated); 
all_phase_mod = combineTables(all_phase_mod, striatum.out.alpha_modulated); 
all_phase_mod = combineTables(all_phase_mod, amygdala.out.alpha_modulated);
all_session_ids = unique(all_phase_mod.session_id);
for s = 1:length(all_session_ids)
    tmp = all_phase_mod(strcmp(all_phase_mod.session_id, all_session_ids{s}),:);
    fracs_lick(s) = sum(tmp.p_lick < pfc.out.overall_p_threshold) / size(tmp,1) * 100;
    fracs_nolick(s) = sum(tmp.p_nolick < pfc.out.overall_p_threshold) / size(tmp,1) * 100;
end
all_fig = figure();
hold on 
bar(1:2, [nanmean(fracs_nolick), nanmean(fracs_lick)], 'FaceColor', [0.5, 0.5, 0.5], 'EdgeColor', [0.5, 0.5, 0.5])
errorbar(1:2, [nanmean(fracs_nolick), nanmean(fracs_lick)], [ste(fracs_nolick), ste(fracs_lick)], 'k.')
xticks(1:2)
xticklabels({'Lick', 'No Lick'})
ylabel('Percent Phase Modulated')